export const FETCH_MOVIE_DETAIL_REQUEST = 'FETCH_ALL_MOVIE_REQUEST';
export const FETCH_MOVIE_DETAIL_SUCCESS = 'FETCH_ALL_MOVIE_SUCCESS';
export const FETCH_MOVIE_DETAIL_FAIL = 'FETCH_ALL_MOVIE_FAIL';